version: "3.3"

services:
  redis:
    restart: always
    image: redis:5-alpine
    container_name: cache_db
    expose:
      - "6379"
    ports:
      - "6379:6379"
  app:
    build: .
    depends_on:
      - redis
    command: npm run server
    volumes:
      - .:/app
    ports:
      - "3000:3000"

  worker:
    build: .
    depends_on:
      - redis
    volumes:
      - .:/app
    command: npm run worker
