version: "3.3"

services:
  app:
    build: .
    command: npm run server
    volumes:
      - .:/app
    ports:
      - "3000:3000"

  worker:
    build: .
    volumes:
      - .:/app
    command: npm run worker
